db:
    image: dockerfile/mongodb
    ports:
        - 27017
rabbit:
    image: rabbitmq
    ports:
        - 15672
web:
    build: .
    command: npm start
    volumes:
        - ./coverage:/src/coverage
        - ./test:/src/test
        - ./api:/src/api
        - ./routes:/src/routes
        - ./app.js:/src/app.js
    ports:
        - 3000:3000
    links:
        - db
        - rabbit
    environment:
        DEBUG: raspberry-pi-io-api:*
        NODE_ENV: development
        JWT_SECRET: fakeToken
        JWT_EXPIRES: 20160
        SYSTEM_API_KEY: fakeapikey
